# Configuration for a docker compose environment
spring:
  datasource:
    url: jdbc:postgresql://db/moneymanagement
    username: postgres
    password: changeme
    driver-class-name: org.postgresql.Driver

rest:
  finnhub:
    url: https://finnhub.io/api/v1/
    token: brjsqrnrh5r9g3otb490
  ecb:
    url: https://api.exchangeratesapi.io/{date}