server:
  port: 8080
  servlet:
    session:
      cookie:
        http-only: true
        secure: true
    context-path: /api/v1
  error:
    include-message: always

spring:
  main:
    allow-bean-definition-overriding: true
  cache:
    jcache:
      config: classpath:ehcache.xml

  jpa:
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect
    show-sql: false
    hibernate:
      ddl-auto: update
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyJpaCompliantImpl
      validator:
        apply_to_ddl: true
    properties:
      hibernate.order_by.default_null_ordering: first

rest:
  finnhub:
    url: https://finnhub.io/api/v1/
    tokens: brjsqrnrh5r9g3otb490,bue1ibv48v6vkac92f90
  ecb:
    url: https://api.exchangeratesapi.io/{date}

app:
  scheduling:
    waiting-time: 60000